### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [kleinesfilmroellchen/spcasm#3]
Maybe this one goes better than kleinesfilmroellchen/sof-language#2:
- [x] Implement `org` macro for sections. We already have section handling in the final assembly step so this shouldn't be too hard.
- [x] Implement the last couple of complex bit commands with `/`, which would complete the implementation of all instructions.
- [x] Implement some basic macros:
    - [x] db
    - [x] ascii
    - [x] asciiz
    - [x] end
    - [x] include
    - [x] incbin
- [ ] Implement `pushsection` and `popsection` without arguments, though we have no sections. These just act on orgs.
- [x] Implement `.label` local labels.
